### ISSUE TITLE
Cho quyền contribute nhanh Kuro

### ISSUE THREAD

**Issue by Menhera-Chan-cool** [KuroHere/kurohack#3]
Skid Senerity
Skid Senerity
Skid Senerity
Skid Senerity
Skid Senerity
Skid Senerity
Skid Senerity
Skid Senerity
Skid Senerity

**Comment by Francescounv2** [comment]
FAKE FAKE

**Comment by Menhera-Chan-cool** [comment]
GIve nhanh
